export type ZoneNames = readonly [string, string, string, string, string]

export const ZONES: Readonly<Record<string, readonly [number, number, ZoneNames]>> = {
  'Africa/Abidjan': [5.32, -4.03, ['Abidjan', '阿比讓', '阿比让', 'アビジャン', '아비장']],
  'Africa/Accra': [5.55, -0.22, ['Accra', '阿克拉', '阿克拉', 'アクラ', '아크라']],
  'Africa/Addis_Ababa': [9.03, 38.7, ['Addis Ababa', '阿迪斯阿貝巴', '亚的斯亚贝巴', 'アジスアベバ', '아디스아바바']],
  'Africa/Algiers': [36.78, 3.05, ['Algiers', '阿爾及爾', '阿尔及尔', 'アルジェ', '알제']],
  'Africa/Asmara': [15.33, 38.88, ['Asmara', '阿斯瑪拉', '阿斯马拉', 'アスマラ', '아스메라']],
  'Africa/Bamako': [12.65, -8.0, ['Bamako', '巴馬科', '巴马科', 'バマコ', '바마코']],
  'Africa/Bangui': [4.37, 18.58, ['Bangui', '班吉', '班吉', 'バンギ', '방기']],
  'Africa/Banjul': [13.47, -16.65, ['Banjul', '班竹', '班珠尔', 'バンジュール', '반줄']],
  'Africa/Bissau': [11.85, -15.58, ['Bissau', '比紹', '比绍', 'ビサウ', '비사우']],
  'Africa/Blantyre': [-15.78, 35.0, ['Blantyre', '布蘭太爾', '布兰太尔', 'ブランタイヤ', '블랜타이어']],
  'Africa/Brazzaville': [-4.27, 15.28, ['Brazzaville', '布拉柴維爾', '布拉柴维尔', 'ブラザビル', '브라자빌']],
  'Africa/Bujumbura': [-3.38, 29.37, ['Bujumbura', '布松布拉', '布琼布拉', 'ブジュンブラ', '부줌부라']],
  'Africa/Cairo': [30.05, 31.25, ['Cairo', '開羅', '开罗', 'カイロ', '카이로']],
  'Africa/Casablanca': [33.65, -7.58, ['Casablanca', '卡薩布蘭卡', '卡萨布兰卡', 'カサブランカ', '카사블랑카']],
  'Africa/Ceuta': [35.88, -5.32, ['Ceuta', '休達', '休达', 'セウタ', '세우타']],
  'Africa/Conakry': [9.52, -13.72, ['Conakry', '柯那克里', '科纳克里', 'コナクリ', '코나크리']],
  'Africa/Dakar': [14.67, -17.43, ['Dakar', '達喀爾', '达喀尔', 'ダカール', '다카르']],
  'Africa/Dar_es_Salaam': [-6.8, 39.28, ['Dar es Salaam', '沙蘭港', '达累斯萨拉姆', 'ダルエスサラーム', '다르에스살람']],
  'Africa/Djibouti': [11.6, 43.15, ['Djibouti', '吉布地', '吉布提', 'ジブチ', '지부티']],
  'Africa/Douala': [4.05, 9.7, ['Douala', '杜阿拉', '杜阿拉', 'ドゥアラ', '두알라']],
  'Africa/El_Aaiun': [27.15, -13.2, ['El Aaiún', '阿尤恩', '阿尤恩', 'アイウン', '엘아이운']],
  'Africa/Freetown': [8.5, -13.25, ['Freetown', '自由城', '弗里敦', 'フリータウン', '프리타운']],
  'Africa/Gaborone': [-24.65, 25.92, ['Gaborone', '嘉柏隆里', '哈博罗内', 'ハボローネ', '가보로네']],
  'Africa/Harare': [-17.83, 31.05, ['Harare', '哈拉雷', '哈拉雷', 'ハラレ', '하라레']],
  'Africa/Johannesburg': [-26.25, 28.0, ['Johannesburg', '約翰尼斯堡', '约翰内斯堡', 'ヨハネスブルグ', '요하네스버그']],
  'Africa/Juba': [4.85, 31.62, ['Juba', '朱巴', '朱巴', 'ジュバ', '주바']],
  'Africa/Kampala': [0.32, 32.42, ['Kampala', '坎帕拉', '坎帕拉', 'カンパラ', '캄팔라']],
  'Africa/Khartoum': [15.6, 32.53, ['Khartoum', '喀土穆', '喀土穆', 'ハルツーム', '카르툼']],
  'Africa/Kigali': [-1.95, 30.07, ['Kigali', '基加利', '基加利', 'キガリ', '키갈리']],
  'Africa/Kinshasa': [-4.3, 15.3, ['Kinshasa', '金夏沙', '金沙萨', 'キンシャサ', '킨샤사']],
  'Africa/Lagos': [6.45, 3.4, ['Lagos', '拉哥斯', '拉各斯', 'ラゴス', '라고스']],
  'Africa/Libreville': [0.38, 9.45, ['Libreville', '自由市', '利伯维尔', 'リーブルヴィル', '리브르빌']],
  'Africa/Lome': [6.13, 1.22, ['Lomé', '洛美', '洛美', 'ロメ', '로메']],
  'Africa/Luanda': [-8.8, 13.23, ['Luanda', '羅安達', '罗安达', 'ルアンダ', '루안다']],
  'Africa/Lubumbashi': [-11.67, 27.47, ['Lubumbashi', '盧本巴希', '卢本巴希', 'ルブンバシ', '루붐바시']],
  'Africa/Lusaka': [-15.42, 28.28, ['Lusaka', '路沙卡', '卢萨卡', 'ルサカ', '루사카']],
  'Africa/Malabo': [3.75, 8.78, ['Malabo', '馬拉博', '马拉博', 'マラボ', '말라보']],
  'Africa/Maputo': [-25.97, 32.58, ['Maputo', '馬普托', '马普托', 'マプト', '마푸토']],
  'Africa/Maseru': [-29.47, 27.5, ['Maseru', '馬賽魯', '马塞卢', 'マセル', '마세루']],
  'Africa/Mbabane': [-26.3, 31.1, ['Mbabane', '墨巴本', '姆巴巴纳', 'ムババーネ', '음바바네']],
  'Africa/Mogadishu': [2.07, 45.37, ['Mogadishu', '摩加迪休', '摩加迪沙', 'モガディシオ', '모가디슈']],
  'Africa/Monrovia': [6.3, -10.78, ['Monrovia', '蒙羅維亞', '蒙罗维亚', 'モンロビア', '몬로비아']],
  'Africa/Nairobi': [-1.28, 36.82, ['Nairobi', '奈洛比', '内罗毕', 'ナイロビ', '나이로비']],
  'Africa/Ndjamena': [12.12, 15.05, ['N’Djamena', '恩賈梅納', '恩贾梅纳', 'ンジャメナ', '엔자메나']],
  'Africa/Niamey': [13.52, 2.12, ['Niamey', '尼亞美', '尼亚美', 'ニアメ', '니아메']],
  'Africa/Nouakchott': [18.1, -15.95, ['Nouakchott', '諾克少', '努瓦克肖特', 'ヌアクショット', '누악쇼트']],
  'Africa/Ouagadougou': [12.37, -1.52, ['Ouagadougou', '瓦加杜古', '瓦加杜古', 'ワガドゥグー', '와가두구']],
  'Africa/Porto-Novo': [6.48, 2.62, ['Porto-Novo', '波多諾佛', '波多诺伏', 'ポルトノボ', '포르토노보']],
  'Africa/Sao_Tome': [0.33, 6.73, ['São Tomé', '聖多美', '圣多美', 'サントメ', '상투메']],
  'Africa/Tripoli': [32.9, 13.18, ['Tripoli', '的黎波里', '的黎波里', 'トリポリ', '트리폴리']],
  'Africa/Tunis': [36.8, 10.18, ['Tunis', '突尼斯', '突尼斯', 'チュニス', '튀니스']],
  'Africa/Windhoek': [-22.57, 17.1, ['Windhoek', '溫得和克', '温得和克', 'ウィントフック', '빈트후크']],
  'America/Adak': [51.88, -176.66, ['Adak', '艾達克', '埃达克', 'アダック', '에이닥']],
  'America/Anchorage': [61.22, -149.9, ['Anchorage', '安克拉治', '安克雷奇', 'アンカレッジ', '앵커리지']],
  'America/Anguilla': [18.2, -63.07, ['Anguilla', '安奎拉', '安圭拉', 'アンギラ', '앙귈라']],
  'America/Antigua': [17.05, -61.8, ['Antigua', '安地卡', '安提瓜', 'アンティグア', '안티과']],
  'America/Araguaina': [-7.2, -48.2, ['Araguaína', '阿拉圭那', '阿拉瓜伊纳', 'アラグァイナ', '아라과이나']],
  'America/Argentina/Buenos_Aires': [-34.6, -58.45, ['Buenos Aires', '布宜諾斯艾利斯', '布宜诺斯艾利斯', 'ブエノスアイレス', '부에노스 아이레스']],
  'America/Argentina/Catamarca': [-28.47, -65.78, ['Catamarca', '卡塔馬卡', '卡塔马卡', 'カタマルカ', '카타마르카']],
  'America/Argentina/Cordoba': [-31.4, -64.18, ['Córdoba', '哥多華', '科尔多瓦', 'コルドバ', '코르도바']],
  'America/Argentina/Jujuy': [-24.18, -65.3, ['Jujuy', '胡胡伊', '胡胡伊', 'フフイ', '후후이']],
  'America/Argentina/La_Rioja': [-29.43, -66.85, ['La Rioja', '拉略哈', '拉里奥哈', 'ラリオハ', '라 리오하']],
  'America/Argentina/Mendoza': [-32.88, -68.82, ['Mendoza', '門多薩', '门多萨', 'メンドーサ', '멘도사']],
  'America/Argentina/Rio_Gallegos': [-51.63, -69.22, ['Río Gallegos', '里奧加耶戈斯', '里奥加耶戈斯', 'リオガジェゴス', '리오 가예고스']],
  'America/Argentina/Salta': [-24.78, -65.42, ['Salta', '薩爾塔', '萨尔塔', 'サルタ', '살타']],
  'America/Argentina/San_Juan': [-31.53, -68.52, ['San Juan', '聖胡安', '圣胡安', 'サンファン', '산후안']],
  'America/Argentina/San_Luis': [-33.32, -66.35, ['San Luis', '聖路易', '圣路易斯', 'サンルイス', '산루이스']],
  'America/Argentina/Tucuman': [-26.82, -65.22, ['Tucumán', '吐庫曼', '图库曼', 'トゥクマン', '투쿠만']],
  'America/Argentina/Ushuaia': [-54.8, -68.3, ['Ushuaia', '烏斯懷亞', '乌斯怀亚', 'ウシュアイア', '우수아이아']],
  'America/Aruba': [12.5, -69.97, ['Aruba', '荷屬阿魯巴', '阿鲁巴', 'アルバ', '아루바']],
  'America/Asuncion': [-25.27, -57.67, ['Asunción', '亞松森', '亚松森', 'アスンシオン', '아순시온']],
  'America/Atikokan': [48.76, -91.62, ['Atikokan', '阿蒂科肯', '阿蒂科肯', 'アティコカン', '코랄하버']],
  'America/Bahia': [-12.98, -38.52, ['Bahia', '巴伊阿', '巴伊亚', 'バイーア', '바히아']],
  'America/Bahia_Banderas': [20.8, -105.25, ['Bahía de Banderas', '巴伊亞班德拉斯', '巴伊亚班德拉斯', 'バイアバンデラ', '바이아 반데라스']],
  'America/Barbados': [13.1, -59.62, ['Barbados', '巴貝多', '巴巴多斯', 'バルバドス', '바베이도스']],
  'America/Belem': [-1.45, -48.48, ['Belém', '貝倫', '贝伦', 'ベレン', '벨렘']],
  'America/Belize': [17.5, -88.2, ['Belize', '貝里斯', '伯利兹', 'ベリーズ', '벨리즈']],
  'America/Blanc-Sablon': [51.42, -57.12, ['Blanc-Sablon', '白朗薩布隆', '布兰克萨布隆', 'ブラン・サブロン', '블랑 사블롱']],
  'America/Boa_Vista': [2.82, -60.67, ['Boa Vista', '保維斯塔', '博阿维斯塔', 'ボアビスタ', '보아 비스타']],
  'America/Bogota': [4.6, -74.08, ['Bogotá', '波哥大', '波哥大', 'ボゴタ', '보고타']],
  'America/Boise': [43.61, -116.2, ['Boise', '波夕', '博伊西', 'ボイシ', '보이시']],
  'America/Cambridge_Bay': [69.11, -105.05, ['Cambridge Bay', '劍橋灣', '剑桥湾', 'ケンブリッジベイ', '케임브리지 베이']],
  'America/Campo_Grande': [-20.45, -54.62, ['Campo Grande', '格蘭場', '大坎普', 'カンポグランデ', '캄포 그란데']],
  'America/Cancun': [21.08, -86.77, ['Cancún', '坎昆', '坎昆', 'カンクン', '칸쿤']],
  'America/Caracas': [10.5, -66.93, ['Caracas', '卡拉卡斯', '加拉加斯', 'カラカス', '카라카스']],
  'America/Cayenne': [4.93, -52.33, ['Cayenne', '開雲', '卡宴', 'カイエンヌ', '카옌']],
  'America/Cayman': [19.3, -81.38, ['Cayman', '開曼群島', '开曼', 'ケイマン', '케이맨']],
  'America/Chicago': [41.85, -87.65, ['Chicago', '芝加哥', '芝加哥', 'シカゴ', '시카고']],
  'America/Chihuahua': [28.63, -106.08, ['Chihuahua', '奇華華', '奇瓦瓦', 'チワワ', '치와와']],
  'America/Ciudad_Juarez': [31.73, -106.48, ['Ciudad Juárez', '華雷斯', '华雷斯城', 'シウダー・フアレス', '시우다드후아레스']],
  'America/Costa_Rica': [9.93, -84.08, ['Costa Rica', '哥斯大黎加', '哥斯达黎加', 'コスタリカ', '코스타리카']],
  'America/Coyhaique': [-45.57, -72.07, ['Coyhaique', '科伊艾克', '科伊艾克', 'コジャイケ', '코이아이케']],
  'America/Creston': [49.1, -116.52, ['Creston', '克雷斯頓', '克雷斯顿', 'クレストン', '크레스톤']],
  'America/Cuiaba': [-15.58, -56.08, ['Cuiabá', '古雅巴', '库亚巴', 'クイアバ', '쿠이아바']],
  'America/Curacao': [12.18, -69.0, ['Curaçao', '庫拉索', '库拉索', 'キュラソー', '퀴라소']],
  'America/Danmarkshavn': [76.77, -18.67, ['Danmarkshavn', '丹馬沙文', '丹马沙文', 'デンマークシャウン', '덴마크샤븐']],
  'America/Dawson': [64.07, -139.42, ['Dawson', '道森', '道森', 'ドーソン', '도슨']],
  'America/Dawson_Creek': [55.77, -120.23, ['Dawson Creek', '道森克里克', '道森克里克', 'ドーソンクリーク', '도슨크릭']],
  'America/Denver': [39.74, -104.98, ['Denver', '丹佛', '丹佛', 'デンバー', '덴버']],
  'America/Detroit': [42.33, -83.05, ['Detroit', '底特律', '底特律', 'デトロイト', '디트로이트']],
  'America/Dominica': [15.3, -61.4, ['Dominica', '多米尼克', '多米尼加', 'ドミニカ', '도미니카']],
  'America/Edmonton': [53.55, -113.47, ['Edmonton', '艾德蒙吞', '埃德蒙顿', 'エドモントン', '에드먼턴']],
  'America/Eirunepe': [-6.67, -69.87, ['Eirunepé', '艾魯內佩', '依伦尼贝', 'エイルネペ', '아이루네페']],
  'America/El_Salvador': [13.7, -89.2, ['El Salvador', '薩爾瓦多', '萨尔瓦多', 'エルサルバドル', '엘살바도르']],
  'America/Fort_Nelson': [58.8, -122.7, ['Fort Nelson', '納爾遜堡', '纳尔逊堡', 'フォートネルソン', '포트 넬슨']],
  'America/Fortaleza': [-3.72, -38.5, ['Fortaleza', '福塔力莎', '福塔雷萨', 'フォルタレザ', '포르탈레자']],
  'America/Glace_Bay': [46.2, -59.95, ['Glace Bay', '格雷斯貝', '格莱斯贝', 'グレースベイ', '글라스베이']],
  'America/Goose_Bay': [53.33, -60.42, ['Goose Bay', '鵝灣', '古斯湾', 'グースベイ', '구즈베이']],
  'America/Grand_Turk': [21.47, -71.13, ['Grand Turk', '大特克島', '大特克', 'グランドターク', '그랜드 터크']],
  'America/Grenada': [12.05, -61.75, ['Grenada', '格瑞納達', '格林纳达', 'グレナダ', '그레나다']],
  'America/Guadeloupe': [16.23, -61.53, ['Guadeloupe', '瓜地洛普', '瓜德罗普', 'グアドループ', '과들루프']],
  'America/Guatemala': [14.63, -90.52, ['Guatemala', '瓜地馬拉', '危地马拉', 'グアテマラ', '과테말라']],
  'America/Guayaquil': [-2.17, -79.83, ['Guayaquil', '瓜亞基爾', '瓜亚基尔', 'グアヤキル', '과야킬']],
  'America/Guyana': [6.8, -58.17, ['Guyana', '蓋亞那', '圭亚那', 'ガイアナ', '가이아나']],
  'America/Halifax': [44.65, -63.6, ['Halifax', '哈里法克斯', '哈利法克斯', 'ハリファクス', '핼리팩스']],
  'America/Havana': [23.13, -82.37, ['Havana', '哈瓦那', '哈瓦那', 'ハバナ', '하바나']],
  'America/Hermosillo': [29.07, -110.97, ['Hermosillo', '埃莫西約', '埃莫西约', 'エルモシヨ', '에르모시요']],
  'America/Indiana/Indianapolis': [39.77, -86.16, ['Indianapolis', '印第安那波里斯', '印第安纳波利斯', 'インディアナポリス', '인디애나폴리스']],
  'America/Indiana/Knox': [41.3, -86.62, ['Knox, Indiana', '印第安那州諾克斯', '印第安纳州诺克斯', 'インディアナ州ノックス', '인디애나주, 녹스']],
  'America/Indiana/Marengo': [38.38, -86.34, ['Marengo, Indiana', '印第安那州馬倫哥', '印第安纳州马伦戈', 'インディアナ州マレンゴ', '인디애나주, 머렝고']],
  'America/Indiana/Petersburg': [38.49, -87.28, ['Petersburg, Indiana', '印第安那州彼得堡', '印第安纳州彼得斯堡', 'インディアナ州ピーターズバーグ', '인디애나주, 피츠버그']],
  'America/Indiana/Tell_City': [37.95, -86.76, ['Tell City, Indiana', '印第安那州泰爾城', '印第安纳州特尔城', 'インディアナ州テルシティ', '인디애나주, 텔시티']],
  'America/Indiana/Vevay': [38.75, -85.07, ['Vevay, Indiana', '印第安那州維威', '印第安纳州维维市', 'インディアナ州ビベー', '인디애나주, 비비']],
  'America/Indiana/Vincennes': [38.68, -87.53, ['Vincennes, Indiana', '印第安那州溫森斯', '印第安纳州温森斯', 'インディアナ州ビンセンス', '인디애나주, 빈센스']],
  'America/Indiana/Winamac': [41.05, -86.6, ['Winamac, Indiana', '印第安那州威納馬克', '印第安纳州威纳马克', 'インディアナ州ウィナマック', '인디애나주, 위너맥']],
  'America/Inuvik': [68.35, -133.72, ['Inuvik', '伊奴維克', '伊努维克', 'イヌヴィク', '이누빅']],
  'America/Iqaluit': [63.73, -68.47, ['Iqaluit', '伊魁特', '伊魁特', 'イカルイット', '이칼루이트']],
  'America/Jamaica': [17.97, -76.79, ['Jamaica', '牙買加', '牙买加', 'ジャマイカ', '자메이카']],
  'America/Juneau': [58.3, -134.42, ['Juneau', '朱諾', '朱诺', 'ジュノー', '주노']],
  'America/Kentucky/Louisville': [38.25, -85.76, ['Louisville', '路易斯維爾', '路易斯维尔', 'ルイビル', '루이빌']],
  'America/Kentucky/Monticello': [36.83, -84.85, ['Monticello, Kentucky', '肯塔基州蒙地卻羅', '肯塔基州蒙蒂塞洛', 'ケンタッキー州モンティチェロ', '켄터키주, 몬티첼로']],
  'America/Kralendijk': [12.15, -68.28, ['Kralendijk', '克拉倫代克', '克拉伦代克', 'クラレンダイク', '크라렌디즈크']],
  'America/La_Paz': [-16.5, -68.15, ['La Paz', '拉巴斯', '拉巴斯', 'ラパス', '라파스']],
  'America/Lima': [-12.05, -77.05, ['Lima', '利馬', '利马', 'リマ', '리마']],
  'America/Los_Angeles': [34.05, -118.24, ['Los Angeles', '洛杉磯', '洛杉矶', 'ロサンゼルス', '로스앤젤레스']],
  'America/Lower_Princes': [18.05, -63.05, ['Lower Prince’s Quarter', '下太子區', '下太子区', 'ローワー・プリンセズ・クウォーター', '로워 프린스 쿼터']],
  'America/Maceio': [-9.67, -35.72, ['Maceió', '馬瑟歐', '马塞约', 'マセイオ', '마세이오']],
  'America/Managua': [12.15, -86.28, ['Managua', '馬拿瓜', '马那瓜', 'マナグア', '마나과']],
  'America/Manaus': [-3.13, -60.02, ['Manaus', '瑪瑙斯', '马瑙斯', 'マナウス', '마나우스']],
  'America/Marigot': [18.07, -63.08, ['Marigot', '馬里戈特', '马里戈特', 'マリゴ', '마리곳']],
  'America/Martinique': [14.6, -61.08, ['Martinique', '馬丁尼克', '马提尼克', 'マルティニーク', '마티니크']],
  'America/Matamoros': [25.83, -97.5, ['Matamoros', '馬塔莫羅斯', '马塔莫罗斯', 'マタモロス', '마타모로스']],
  'America/Mazatlan': [23.22, -106.42, ['Mazatlán', '馬薩特蘭', '马萨特兰', 'マサトラン', '마사틀란']],
  'America/Menominee': [45.11, -87.61, ['Menominee', '美諾米尼', '梅诺米尼', 'メノミニー', '메노미니']],
  'America/Merida': [20.97, -89.62, ['Mérida', '梅里達', '梅里达', 'メリダ', '메리다']],
  'America/Metlakatla': [55.13, -131.58, ['Metlakatla', '梅特拉卡特拉', '梅特拉卡特拉', 'メトラカトラ', '메틀라카틀라']],
  'America/Mexico_City': [19.4, -99.15, ['Mexico City', '墨西哥市', '墨西哥城', 'メキシコシティー', '멕시코 시티']],
  'America/Miquelon': [47.05, -56.33, ['Saint-Pierre', '密啟崙', '密克隆', 'ミクロン島', '미클롱']],
  'America/Moncton': [46.1, -64.78, ['Moncton', '蒙克頓', '蒙克顿', 'モンクトン', '몽턴']],
  'America/Monterrey': [25.67, -100.32, ['Monterrey', '蒙特瑞', '蒙特雷', 'モンテレイ', '몬테레이']],
  'America/Montevideo': [-34.91, -56.21, ['Montevideo', '蒙特維多', '蒙得维的亚', 'モンテビデオ', '몬테비데오']],
  'America/Montserrat': [16.72, -62.22, ['Montserrat', '蒙哲臘', '蒙特塞拉特', 'モントセラト', '몬세라트']],
  'America/Nassau': [25.08, -77.35, ['Nassau', '拿索', '拿骚', 'ナッソー', '나소']],
  'America/New_York': [40.71, -74.01, ['New York', '紐約', '纽约', 'ニューヨーク', '뉴욕']],
  'America/Nome': [64.5, -165.41, ['Nome', '諾姆', '诺姆', 'ノーム', '놈']],
  'America/Noronha': [-3.85, -32.42, ['Fernando de Noronha', '諾倫哈', '洛罗尼亚', 'ノローニャ', '노롱야']],
  'America/North_Dakota/Beulah': [47.26, -101.78, ['Beulah, North Dakota', '北達科他州布由拉', '北达科他州比尤拉', 'ノースダコタ州ビューラー', '노스다코타주, 베라']],
  'America/North_Dakota/Center': [47.12, -101.3, ['Center, North Dakota', '北達科他州中心', '北达科他州申特', 'ノースダコタ州センター', '중부, 노스다코타']],
  'America/North_Dakota/New_Salem': [46.84, -101.41, ['New Salem, North Dakota', '北達科他州紐沙倫', '北达科他州新塞勒姆', 'ノースダコタ州ニューセーラム', '노스다코타주, 뉴살렘']],
  'America/Nuuk': [64.18, -51.73, ['Nuuk', '努克', '努克', 'ヌーク', '고드호프']],
  'America/Ojinaga': [29.57, -104.42, ['Ojinaga', '奧希納加', '奥希纳加', 'オヒナガ', '오히나가']],
  'America/Panama': [8.97, -79.53, ['Panama', '巴拿馬', '巴拿马', 'パナマ', '파나마']],
  'America/Paramaribo': [5.83, -55.17, ['Paramaribo', '巴拉馬利波', '帕拉马里博', 'パラマリボ', '파라마리보']],
  'America/Phoenix': [33.45, -112.07, ['Phoenix', '鳳凰城', '凤凰城', 'フェニックス', '피닉스']],
  'America/Port-au-Prince': [18.53, -72.33, ['Port-au-Prince', '太子港', '太子港', 'ポルトープランス', '포르토프랭스']],
  'America/Port_of_Spain': [10.65, -61.52, ['Port of Spain', '西班牙港', '西班牙港', 'ポートオブスペイン', '포트오브스페인']],
  'America/Porto_Velho': [-8.77, -63.9, ['Porto Velho', '維留港', '波多韦柳', 'ポルトベーリョ', '포르토벨료']],
  'America/Puerto_Rico': [18.47, -66.11, ['Puerto Rico', '波多黎各', '波多黎各', 'プエルトリコ', '푸에르토리코']],
  'America/Punta_Arenas': [-53.15, -70.92, ['Punta Arenas', '蓬塔阿雷納斯', '蓬塔阿雷纳斯', 'プンタアレナス', '푼타아레나스']],
  'America/Rankin_Inlet': [62.82, -92.08, ['Rankin Inlet', '蘭今灣', '兰今湾', 'ランキンインレット', '랭킹 인렛']],
  'America/Recife': [-8.05, -34.9, ['Recife', '雷西非', '累西腓', 'レシフェ', '레시페']],
  'America/Regina': [50.4, -104.65, ['Regina', '里賈納', '里贾纳', 'レジャイナ', '리자이나']],
  'America/Resolute': [74.7, -94.83, ['Resolute', '羅斯魯特', '雷索卢特', 'レゾリュート', '리졸루트']],
  'America/Rio_Branco': [-9.97, -67.8, ['Rio Branco', '里約布蘭', '里奥布郎库', 'リオブランコ', '히우 브랑쿠']],
  'America/Santarem': [-2.43, -54.87, ['Santarém', '聖塔倫', '圣塔伦', 'サンタレム', '산타렘']],
  'America/Santiago': [-33.45, -70.67, ['Santiago', '聖地牙哥', '圣地亚哥', 'サンチアゴ', '산티아고']],
  'America/Santo_Domingo': [18.47, -69.9, ['Santo Domingo', '聖多明哥', '圣多明各', 'サントドミンゴ', '산토도밍고']],
  'America/Sao_Paulo': [-23.53, -46.62, ['São Paulo', '聖保羅', '圣保罗', 'サンパウロ', '상파울루']],
  'America/Scoresbysund': [70.48, -21.97, ['Ittoqqortoormiit', '伊托科爾托米特', '斯科列斯比桑德', 'イトコルトルミット', '스코레스바이선드']],
  'America/Sitka': [57.18, -135.3, ['Sitka', '錫特卡', '锡特卡', 'シトカ', '싯카']],
  'America/St_Barthelemy': [17.88, -62.85, ['St. Barthélemy', '聖巴托洛繆島', '圣巴泰勒米岛', 'サン・バルテルミー', '생바르텔레미']],
  'America/St_Johns': [47.57, -52.72, ['St. John’s', '聖約翰', '圣约翰斯', 'セントジョンズ', '세인트존스']],
  'America/St_Kitts': [17.3, -62.72, ['St. Kitts', '聖基茨', '圣基茨', 'セントクリストファー', '세인트키츠']],
  'America/St_Lucia': [14.02, -61.0, ['St. Lucia', '聖露西亞', '圣卢西亚', 'セントルシア', '세인트루시아']],
  'America/St_Thomas': [18.35, -64.93, ['St. Thomas', '聖托馬斯', '圣托马斯', 'セントトーマス', '세인트토마스']],
  'America/St_Vincent': [13.15, -61.23, ['St. Vincent', '聖文森', '圣文森特', 'セントビンセント', '세인트빈센트']],
  'America/Swift_Current': [50.28, -107.83, ['Swift Current', '斯威夫特卡倫特', '斯威夫特卡伦特', 'スウィフトカレント', '스위프트커런트']],
  'America/Tegucigalpa': [14.1, -87.22, ['Tegucigalpa', '德古斯加巴', '特古西加尔巴', 'テグシガルパ', '테구시갈파']],
  'America/Thule': [76.57, -68.78, ['Thule', '杜里', '图勒', 'チューレ', '툴레']],
  'America/Tijuana': [32.53, -117.02, ['Tijuana', '提華納', '蒂华纳', 'ティフアナ', '티후아나']],
  'America/Toronto': [43.65, -79.38, ['Toronto', '多倫多', '多伦多', 'トロント', '토론토']],
  'America/Tortola': [18.45, -64.62, ['Tortola', '托爾托拉', '托尔托拉', 'トルトーラ', '토르톨라']],
  'America/Vancouver': [49.27, -123.12, ['Vancouver', '溫哥華', '温哥华', 'バンクーバー', '벤쿠버']],
  'America/Whitehorse': [60.72, -135.05, ['Whitehorse', '懷特霍斯', '怀特霍斯', 'ホワイトホース', '화이트호스']],
  'America/Winnipeg': [49.88, -97.15, ['Winnipeg', '溫尼伯', '温尼伯', 'ウィニペグ', '위니펙']],
  'America/Yakutat': [59.55, -139.73, ['Yakutat', '雅庫塔', '亚库塔特', 'ヤクタット', '야쿠타트']],
  'Antarctica/Casey': [-66.28, 110.52, ['Casey Station', '凱西', '卡塞', 'ケーシー基地', '케이시']],
  'Antarctica/Davis': [-68.58, 77.97, ['Davis', '戴維斯', '戴维斯', 'デービス基地', '데이비스']],
  'Antarctica/DumontDUrville': [-66.67, 140.02, ['Dumont d’Urville Station', '杜蒙杜比爾', '迪蒙·迪维尔', 'デュモン・デュルヴィル基地', '뒤몽 뒤르빌']],
  'Antarctica/Macquarie': [-54.5, 158.95, ['Macquarie Island', '麥覺理', '麦夸里岛', 'マッコリー', '맥쿼리']],
  'Antarctica/Mawson': [-67.6, 62.88, ['Mawson Station', '莫森', '莫森', 'モーソン基地', '모슨']],
  'Antarctica/McMurdo': [-77.83, 166.6, ['McMurdo Station', '麥克默多', '麦克默多', 'マクマード基地', '맥머도']],
  'Antarctica/Palmer': [-64.8, -64.1, ['Palmer Land', '帕麥', '帕尔默', 'パーマー基地', '파머']],
  'Antarctica/Rothera': [-67.57, -68.13, ['Rothera Station', '羅瑟拉', '罗瑟拉', 'ロゼラ基地', '로데라']],
  'Antarctica/Syowa': [-69.01, 39.59, ['Showa Station', '昭和基地', '昭和', '昭和基地', '쇼와']],
  'Antarctica/Troll': [-72.01, 2.53, ['Troll Station', '綽爾', '特罗尔', 'トロル基地', '트롤']],
  'Antarctica/Vostok': [-78.4, 106.9, ['Vostok Station', '沃斯托克', '沃斯托克', 'ボストーク基地', '보스토크']],
  'Arctic/Longyearbyen': [78.0, 16.0, ['Longyearbyen', '隆意耳拜恩', '朗伊尔城', 'ロングイェールビーン', '롱이어비엔']],
  'Asia/Aden': [12.75, 45.2, ['Aden', '亞丁', '亚丁', 'アデン', '아덴']],
  'Asia/Almaty': [43.25, 76.95, ['Almaty', '阿拉木圖', '阿拉木图', 'アルマトイ', '알마티']],
  'Asia/Amman': [31.95, 35.93, ['Amman', '安曼', '安曼', 'アンマン', '암만']],
  'Asia/Anadyr': [64.75, 177.48, ['Anadyr', '阿那底', '阿纳德尔', 'アナディリ', '아나디리']],
  'Asia/Aqtau': [44.52, 50.27, ['Aktau', '阿克套', '阿克套', 'アクタウ', '아크타우']],
  'Asia/Aqtobe': [50.28, 57.17, ['Aqtobe', '阿克托比', '阿克托别', 'アクトベ', '악토브']],
  'Asia/Ashgabat': [37.95, 58.38, ['Ashgabat', '阿什哈巴特', '阿什哈巴德', 'アシガバード', '아슈하바트']],
  'Asia/Atyrau': [47.12, 51.93, ['Atyrau', '阿特勞', '阿特劳', 'アティラウ', '아티라우']],
  'Asia/Baghdad': [33.35, 44.42, ['Baghdad', '巴格達', '巴格达', 'バグダッド', '바그다드']],
  'Asia/Bahrain': [26.38, 50.58, ['Bahrain', '巴林', '巴林', 'バーレーン', '바레인']],
  'Asia/Baku': [40.38, 49.85, ['Baku', '巴庫', '巴库', 'バクー', '바쿠']],
  'Asia/Bangkok': [13.75, 100.52, ['Bangkok', '曼谷', '曼谷', 'バンコク', '방콕']],
  'Asia/Barnaul': [53.37, 83.75, ['Barnaul', '巴爾瑙爾', '巴尔瑙尔', 'バルナウル', '바르나울']],
  'Asia/Beirut': [33.88, 35.5, ['Beirut', '貝魯特', '贝鲁特', 'ベイルート', '베이루트']],
  'Asia/Bishkek': [42.9, 74.6, ['Bishkek', '比什凱克', '比什凯克', 'ビシュケク', '비슈케크']],
  'Asia/Brunei': [4.93, 114.92, ['Brunei', '汶萊', '文莱', 'ブルネイ', '브루나이']],
  'Asia/Chita': [52.05, 113.47, ['Chita', '赤塔', '赤塔', 'チタ', '치타']],
  'Asia/Colombo': [6.93, 79.85, ['Colombo', '可倫坡', '科伦坡', 'コロンボ', '콜롬보']],
  'Asia/Damascus': [33.5, 36.3, ['Damascus', '大馬士革', '大马士革', 'ダマスカス', '다마스쿠스']],
  'Asia/Dhaka': [23.72, 90.42, ['Dhaka', '達卡', '达卡', 'ダッカ', '다카']],
  'Asia/Dili': [-8.55, 125.58, ['Dili', '帝力', '帝力', 'ディリ', '딜리']],
  'Asia/Dubai': [25.3, 55.3, ['Dubai', '杜拜', '迪拜', 'ドバイ', '두바이']],
  'Asia/Dushanbe': [38.58, 68.8, ['Dushanbe', '杜桑貝', '杜尚别', 'ドゥシャンベ', '두샨베']],
  'Asia/Famagusta': [35.12, 33.95, ['Famagusta', '法馬古斯塔', '法马古斯塔', 'ファマグスタ', '파마구스타']],
  'Asia/Gaza': [31.5, 34.47, ['Gaza', '加薩', '加沙', 'ガザ', '가자']],
  'Asia/Hebron': [31.53, 35.09, ['Hebron', '赫布隆', '希伯伦', 'ヘブロン', '헤브론']],
  'Asia/Ho_Chi_Minh': [10.75, 106.67, ['Ho Chi Minh City', '胡志明市', '胡志明市', 'ホーチミン', '호찌민']],
  'Asia/Hong_Kong': [22.28, 114.15, ['Hong Kong', '香港', '香港', '香港', '홍콩']],
  'Asia/Hovd': [48.02, 91.65, ['Khovd', '科布多', '科布多', 'ホブド', '호브드']],
  'Asia/Irkutsk': [52.27, 104.33, ['Irkutsk', '伊爾庫次克', '伊尔库茨克', 'イルクーツク', '이르쿠츠크']],
  'Asia/Jakarta': [-6.17, 106.8, ['Jakarta', '雅加達', '雅加达', 'ジャカルタ', '자카르타']],
  'Asia/Jayapura': [-2.53, 140.7, ['Jayapura', '加亞布拉', '查亚普拉', 'ジャヤプラ', '자야푸라']],
  'Asia/Jerusalem': [31.78, 35.22, ['Jerusalem', '耶路撒冷', '耶路撒冷', 'エルサレム', '예루살렘']],
  'Asia/Kabul': [34.52, 69.2, ['Kabul', '喀布爾', '喀布尔', 'カブール', '카불']],
  'Asia/Kamchatka': [53.02, 158.65, ['Kamchatka', '堪察加', '堪察加', 'カムチャッカ', '캄차카']],
  'Asia/Karachi': [24.87, 67.05, ['Karachi', '喀拉蚩', '卡拉奇', 'カラチ', '카라치']],
  'Asia/Kathmandu': [27.72, 85.32, ['Kathmandu', '加德滿都', '加德满都', 'カトマンズ', '카트만두']],
  'Asia/Khandyga': [62.66, 135.55, ['Khandyga', '堪地加', '汉德加', 'ハンドゥイガ', '한디가']],
  'Asia/Kolkata': [22.53, 88.37, ['Kolkata', '加爾各答', '加尔各答', 'コルカタ', '콜카타']],
  'Asia/Krasnoyarsk': [56.02, 92.83, ['Krasnoyarsk', '克拉斯諾亞爾斯克', '克拉斯诺亚尔斯克', 'クラスノヤルスク', '크라스노야르스크']],
  'Asia/Kuala_Lumpur': [3.17, 101.7, ['Kuala Lumpur', '吉隆坡', '吉隆坡', 'クアラルンプール', '쿠알라룸푸르']],
  'Asia/Kuching': [1.55, 110.33, ['Kuching', '古晉', '古晋', 'クチン', '쿠칭']],
  'Asia/Kuwait': [29.33, 47.98, ['Kuwait', '科威特', '科威特', 'クウェート', '쿠웨이트']],
  'Asia/Macau': [22.2, 113.54, ['Macao', '澳門', '澳门', 'マカオ', '마카오']],
  'Asia/Magadan': [59.57, 150.8, ['Magadan', '馬加丹', '马加丹', 'マガダン', '마가단']],
  'Asia/Makassar': [-5.12, 119.4, ['Makassar', '馬卡沙爾', '望加锡', 'マカッサル', '마카사르']],
  'Asia/Manila': [14.59, 120.97, ['Manila', '馬尼拉', '马尼拉', 'マニラ', '마닐라']],
  'Asia/Muscat': [23.6, 58.58, ['Muscat', '馬斯開特', '马斯喀特', 'マスカット', '무스카트']],
  'Asia/Nicosia': [35.17, 33.37, ['Nicosia', '尼古西亞', '尼科西亚', 'ニコシア', '니코시아']],
  'Asia/Novokuznetsk': [53.75, 87.12, ['Novokuznetsk', '新庫茲涅茨克', '新库兹涅茨克', 'ノヴォクズネツク', '노보쿠즈네츠크']],
  'Asia/Novosibirsk': [55.03, 82.92, ['Novosibirsk', '新西伯利亞', '新西伯利亚', 'ノヴォシビルスク', '노보시비르스크']],
  'Asia/Omsk': [55.0, 73.4, ['Omsk', '鄂木斯克', '鄂木斯克', 'オムスク', '옴스크']],
  'Asia/Oral': [51.22, 51.35, ['Oral', '烏拉爾', '乌拉尔', 'オラル', '오랄']],
  'Asia/Phnom_Penh': [11.55, 104.92, ['Phnom Penh', '金邊', '金边', 'プノンペン', '프놈펜']],
  'Asia/Pontianak': [-0.03, 109.33, ['Pontianak', '坤甸', '坤甸', 'ポンティアナック', '폰티아나크']],
  'Asia/Pyongyang': [39.02, 125.75, ['Pyongyang', '平壤', '平壤', '平壌', '평양']],
  'Asia/Qatar': [25.28, 51.53, ['Qatar', '卡達', '卡塔尔', 'カタール', '카타르']],
  'Asia/Qostanay': [53.2, 63.62, ['Kostanay', '庫斯塔奈', '库斯塔奈', 'コスタナイ', '코스타나이']],
  'Asia/Qyzylorda': [44.8, 65.47, ['Kyzylorda', '克孜勒奧爾達', '克孜洛尔达', 'クズロルダ', '키질로르다']],
  'Asia/Riyadh': [24.63, 46.72, ['Riyadh', '利雅德', '利雅得', 'リヤド', '리야드']],
  'Asia/Sakhalin': [46.97, 142.7, ['Sakhalin', '庫頁島', '萨哈林', 'サハリン', '사할린']],
  'Asia/Samarkand': [39.67, 66.8, ['Samarkand', '撒馬爾罕', '撒马尔罕', 'サマルカンド', '사마르칸트']],
  'Asia/Seoul': [37.55, 126.97, ['Seoul', '首爾', '首尔', 'ソウル', '서울']],
  'Asia/Shanghai': [31.23, 121.47, ['Shanghai', '上海', '上海', '上海', '상하이']],
  'Asia/Singapore': [1.28, 103.85, ['Singapore', '新加坡', '新加坡', 'シンガポール', '싱가포르']],
  'Asia/Srednekolymsk': [67.47, 153.72, ['Srednekolymsk', '中科雷姆斯克', '中科雷姆斯克', 'スレドネコリムスク', '스레드네콜림스크']],
  'Asia/Taipei': [25.05, 121.5, ['Taipei', '台北', '台北', '台北', '타이베이']],
  'Asia/Tashkent': [41.33, 69.3, ['Tashkent', '塔什干', '塔什干', 'タシケント', '타슈켄트']],
  'Asia/Tbilisi': [41.72, 44.82, ['Tbilisi', '第比利斯', '第比利斯', 'トビリシ', '트빌리시']],
  'Asia/Tehran': [35.67, 51.43, ['Tehran', '德黑蘭', '德黑兰', 'テヘラン', '테헤란']],
  'Asia/Thimphu': [27.47, 89.65, ['Thimphu', '廷布', '廷布', 'ティンプー', '팀부']],
  'Asia/Tokyo': [35.65, 139.74, ['Tokyo', '東京', '东京', '東京', '도쿄']],
  'Asia/Tomsk': [56.5, 84.97, ['Tomsk', '托木斯克', '托木斯克', 'トムスク', '톰스크']],
  'Asia/Ulaanbaatar': [47.92, 106.88, ['Ulaanbaatar', '烏蘭巴托', '乌兰巴托', 'ウランバートル', '울란바토르']],
  'Asia/Urumqi': [43.8, 87.58, ['Ürümqi', '烏魯木齊', '乌鲁木齐', 'ウルムチ', '우루무치']],
  'Asia/Ust-Nera': [64.56, 143.23, ['Ust-Nera', '烏斯內拉', '乌斯内拉', 'ウスチネラ', '우스티네라']],
  'Asia/Vientiane': [17.97, 102.6, ['Vientiane', '永珍', '万象', 'ビエンチャン', '비엔티안']],
  'Asia/Vladivostok': [43.17, 131.93, ['Vladivostok', '海參崴', '海参崴', 'ウラジオストク', '블라디보스토크']],
  'Asia/Yakutsk': [62.0, 129.67, ['Yakutsk', '雅庫次克', '雅库茨克', 'ヤクーツク', '야쿠츠크']],
  'Asia/Yangon': [16.78, 96.17, ['Yangon', '仰光', '仰光', 'ヤンゴン', '양곤']],
  'Asia/Yekaterinburg': [56.85, 60.6, ['Yekaterinburg', '葉卡捷林堡', '叶卡捷琳堡', 'エカテリンブルグ', '예카테린부르크']],
  'Asia/Yerevan': [40.18, 44.5, ['Yerevan', '葉里溫', '埃里温', 'エレバン', '예레반']],
  'Atlantic/Azores': [37.73, -25.67, ['Azores', '亞速爾群島', '亚速尔群岛', 'アゾレス', '아조레스']],
  'Atlantic/Bermuda': [32.28, -64.77, ['Bermuda', '百慕達', '百慕大', 'バミューダ', '버뮤다']],
  'Atlantic/Canary': [28.1, -15.4, ['Canaries', '加納利', '加那利', 'カナリア', '카나리아 제도']],
  'Atlantic/Cape_Verde': [14.92, -23.52, ['Cape Verde', '維德角', '佛得角', 'カーボベルデ', '카보 베르데']],
  'Atlantic/Faroe': [62.02, -6.77, ['Faroes', '法羅群島', '法罗', 'フェロー', '페로 제도']],
  'Atlantic/Madeira': [32.63, -16.9, ['Madeira', '馬得拉群島', '马德拉', 'マデイラ', '마데이라']],
  'Atlantic/Reykjavik': [64.15, -21.85, ['Reykjavik', '雷克雅維克', '雷克雅未克', 'レイキャビク', '레이캬비크']],
  'Atlantic/South_Georgia': [-54.27, -36.53, ['South Georgia', '南喬治亞', '南乔治亚', 'サウスジョージア', '사우스조지아']],
  'Atlantic/St_Helena': [-15.92, -5.7, ['St. Helena', '聖赫勒拿島', '圣赫勒拿', 'セントヘレナ', '세인트 헬레나']],
  'Atlantic/Stanley': [-51.7, -57.85, ['Stanley', '史坦利', '斯坦利', 'スタンレー', '스탠리']],
  'Australia/Adelaide': [-34.92, 138.58, ['Adelaide', '阿得雷德', '阿德莱德', 'アデレード', '애들레이드']],
  'Australia/Brisbane': [-27.47, 153.03, ['Brisbane', '布利斯班', '布里斯班', 'ブリスベン', '브리스베인']],
  'Australia/Broken_Hill': [-31.95, 141.45, ['Broken Hill', '布羅肯希爾', '布罗肯希尔', 'ブロークンヒル', '브로컨힐']],
  'Australia/Darwin': [-12.47, 130.83, ['Darwin', '達爾文', '达尔文', 'ダーウィン', '다윈']],
  'Australia/Eucla': [-31.72, 128.87, ['Eucla', '尤克拉', '尤克拉', 'ユークラ', '유클라']],
  'Australia/Hobart': [-42.88, 147.32, ['Hobart', '荷巴特', '霍巴特', 'ホバート', '호바트']],
  'Australia/Lindeman': [-20.27, 149.0, ['Lindeman', '林德曼', '林德曼', 'リンデマン', '린데만']],
  'Australia/Lord_Howe': [-31.55, 159.08, ['Lord Howe Island', '豪勳爵島', '豪勋爵岛', 'ロードハウ', '로드 하우']],
  'Australia/Melbourne': [-37.82, 144.97, ['Melbourne', '墨爾本', '墨尔本', 'メルボルン', '멜버른']],
  'Australia/Perth': [-31.95, 115.85, ['Perth', '伯斯', '珀斯', 'パース', '퍼스']],
  'Australia/Sydney': [-33.87, 151.22, ['Sydney', '雪梨', '悉尼', 'シドニー', '시드니']],
  'Europe/Amsterdam': [52.37, 4.9, ['Amsterdam', '阿姆斯特丹', '阿姆斯特丹', 'アムステルダム', '암스테르담']],
  'Europe/Andorra': [42.5, 1.52, ['Andorra', '安道爾', '安道尔', 'アンドラ', '안도라']],
  'Europe/Astrakhan': [46.35, 48.05, ['Astrakhan', '阿斯特拉罕', '阿斯特拉罕', 'アストラハン', '아스트라한']],
  'Europe/Athens': [37.97, 23.72, ['Athens', '雅典', '雅典', 'アテネ', '아테네']],
  'Europe/Belgrade': [44.83, 20.5, ['Belgrade', '貝爾格勒', '贝尔格莱德', 'ベオグラード', '베오그라드']],
  'Europe/Berlin': [52.5, 13.37, ['Berlin', '柏林', '柏林', 'ベルリン', '베를린']],
  'Europe/Bratislava': [48.15, 17.12, ['Bratislava', '布拉提斯拉瓦', '布拉迪斯拉发', 'ブラチスラバ', '브라티슬라바']],
  'Europe/Brussels': [50.83, 4.33, ['Brussels', '布魯塞爾', '布鲁塞尔', 'ブリュッセル', '브뤼셀']],
  'Europe/Bucharest': [44.43, 26.1, ['Bucharest', '布加勒斯特', '布加勒斯特', 'ブカレスト', '부쿠레슈티']],
  'Europe/Budapest': [47.5, 19.08, ['Budapest', '布達佩斯', '布达佩斯', 'ブダペスト', '부다페스트']],
  'Europe/Busingen': [47.7, 8.68, ['Büsingen', '布辛根', '布辛根', 'ビュージンゲン', '뷔지겐']],
  'Europe/Chisinau': [47.0, 28.83, ['Chișinău', '基西紐', '基希讷乌', 'キシナウ', '키시나우']],
  'Europe/Copenhagen': [55.67, 12.58, ['Copenhagen', '哥本哈根', '哥本哈根', 'コペンハーゲン', '코펜하겐']],
  'Europe/Dublin': [53.33, -6.25, ['Dublin', '都柏林', '都柏林', 'ダブリン', '더블린']],
  'Europe/Gibraltar': [36.13, -5.35, ['Gibraltar', '直布羅陀', '直布罗陀', 'ジブラルタル', '지브롤터']],
  'Europe/Guernsey': [49.45, -2.54, ['Guernsey', '根息島', '根西岛', 'ガーンジー', '건지']],
  'Europe/Helsinki': [60.17, 24.97, ['Helsinki', '赫爾辛基', '赫尔辛基', 'ヘルシンキ', '헬싱키']],
  'Europe/Isle_of_Man': [54.15, -4.47, ['Isle of Man', '曼島', '马恩岛', 'マン島', '맨섬']],
  'Europe/Istanbul': [41.02, 28.97, ['Istanbul', '伊斯坦堡', '伊斯坦布尔', 'イスタンブール', '이스탄불']],
  'Europe/Jersey': [49.18, -2.11, ['Jersey', '澤西島', '泽西岛', 'ジャージー', '저지']],
  'Europe/Kaliningrad': [54.72, 20.5, ['Kaliningrad', '加里寧格勒', '加里宁格勒', 'カリーニングラード', '칼리닌그라드']],
  'Europe/Kirov': [58.6, 49.65, ['Kirov', '基洛夫', '基洛夫', 'キーロフ', '키로프']],
  'Europe/Kyiv': [50.43, 30.52, ['Kyiv', '基輔', '基辅', 'キーウ', '키예프']],
  'Europe/Lisbon': [38.72, -9.13, ['Lisbon', '里斯本', '里斯本', 'リスボン', '리스본']],
  'Europe/Ljubljana': [46.05, 14.52, ['Ljubljana', '盧比安納', '卢布尔雅那', 'リュブリャナ', '류블랴나']],
  'Europe/London': [51.51, -0.13, ['London', '倫敦', '伦敦', 'ロンドン', '런던']],
  'Europe/Luxembourg': [49.6, 6.15, ['Luxembourg', '盧森堡', '卢森堡', 'ルクセンブルク', '룩셈부르크']],
  'Europe/Madrid': [40.4, -3.68, ['Madrid', '馬德里', '马德里', 'マドリード', '마드리드']],
  'Europe/Malta': [35.9, 14.52, ['Malta', '馬爾他', '马耳他', 'マルタ', '몰타']],
  'Europe/Mariehamn': [60.1, 19.95, ['Mariehamn', '瑪麗港', '玛丽港', 'マリエハムン', '마리에함']],
  'Europe/Minsk': [53.9, 27.57, ['Minsk', '明斯克', '明斯克', 'ミンスク', '민스크']],
  'Europe/Monaco': [43.7, 7.38, ['Monaco', '摩納哥', '摩纳哥', 'モナコ', '모나코']],
  'Europe/Moscow': [55.76, 37.62, ['Moscow', '莫斯科', '莫斯科', 'モスクワ', '모스크바']],
  'Europe/Oslo': [59.92, 10.75, ['Oslo', '奧斯陸', '奥斯陆', 'オスロ', '오슬로']],
  'Europe/Paris': [48.87, 2.33, ['Paris', '巴黎', '巴黎', 'パリ', '파리']],
  'Europe/Podgorica': [42.43, 19.27, ['Podgorica', '波多里察', '波德戈里察', 'ポドゴリツァ', '포드고리차']],
  'Europe/Prague': [50.08, 14.43, ['Prague', '布拉格', '布拉格', 'プラハ', '프라하']],
  'Europe/Riga': [56.95, 24.1, ['Riga', '里加', '里加', 'リガ', '리가']],
  'Europe/Rome': [41.9, 12.48, ['Rome', '羅馬', '罗马', 'ローマ', '로마']],
  'Europe/Samara': [53.2, 50.15, ['Samara', '沙馬拉', '萨马拉', 'サマラ', '사마라']],
  'Europe/San_Marino': [43.92, 12.47, ['San Marino', '聖馬利諾', '圣马力诺', 'サンマリノ', '산마리노']],
  'Europe/Sarajevo': [43.87, 18.42, ['Sarajevo', '塞拉耶佛', '萨拉热窝', 'サラエボ', '사라예보']],
  'Europe/Saratov': [51.57, 46.03, ['Saratov', '薩拉托夫', '萨拉托夫', 'サラトフ', '사라토프']],
  'Europe/Simferopol': [44.95, 34.1, ['Simferopol', '辛非洛浦', '辛菲罗波尔', 'シンフェロポリ', '심페로폴']],
  'Europe/Skopje': [41.98, 21.43, ['Skopje', '史高比耶', '斯科普里', 'スコピエ', '스코페']],
  'Europe/Sofia': [42.68, 23.32, ['Sofia', '索菲亞', '索非亚', 'ソフィア', '소피아']],
  'Europe/Stockholm': [59.33, 18.05, ['Stockholm', '斯德哥爾摩', '斯德哥尔摩', 'ストックホルム', '스톡홀름']],
  'Europe/Tallinn': [59.42, 24.75, ['Tallinn', '塔林', '塔林', 'タリン', '탈린']],
  'Europe/Tirane': [41.33, 19.83, ['Tirana', '地拉那', '地拉那', 'ティラナ', '티라나']],
  'Europe/Ulyanovsk': [54.33, 48.4, ['Ulyanovsk', '烏里揚諾夫斯克', '乌里扬诺夫斯克', 'ウリヤノフスク', '울리야노프스크']],
  'Europe/Vaduz': [47.15, 9.52, ['Vaduz', '瓦都茲', '瓦杜兹', 'ファドゥーツ', '파두츠']],
  'Europe/Vatican': [41.9, 12.45, ['Vatican', '梵蒂岡', '梵蒂冈', 'バチカン', '바티칸']],
  'Europe/Vienna': [48.22, 16.33, ['Vienna', '維也納', '维也纳', 'ウィーン', '비엔나']],
  'Europe/Vilnius': [54.68, 25.32, ['Vilnius', '維爾紐斯', '维尔纽斯', 'ヴィリニュス', '빌니우스']],
  'Europe/Volgograd': [48.73, 44.42, ['Volgograd', '伏爾加格勒', '伏尔加格勒', 'ボルゴグラード', '볼고그라트']],
  'Europe/Warsaw': [52.25, 21.0, ['Warsaw', '華沙', '华沙', 'ワルシャワ', '바르샤바']],
  'Europe/Zagreb': [45.8, 15.97, ['Zagreb', '札格瑞布', '萨格勒布', 'ザグレブ', '자그레브']],
  'Europe/Zurich': [47.38, 8.53, ['Zurich', '蘇黎世', '苏黎世', 'チューリッヒ', '취리히']],
  'Indian/Antananarivo': [-18.92, 47.52, ['Antananarivo', '安塔那那利弗', '安塔那那利佛', 'アンタナナリボ', '안타나나리보']],
  'Indian/Chagos': [-7.33, 72.42, ['Chagos Archipelago', '查戈斯', '查戈斯', 'チャゴス', '차고스']],
  'Indian/Christmas': [-10.42, 105.72, ['Christmas Island', '聖誕島', '圣诞岛', 'クリスマス島', '크리스마스']],
  'Indian/Cocos': [-12.17, 96.92, ['Cocos Islands', '科科斯群島', '可可斯', 'ココス諸島', '코코스']],
  'Indian/Comoro': [-11.68, 43.27, ['Comoros', '科摩羅群島', '科摩罗', 'コモロ', '코모로']],
  'Indian/Kerguelen': [-49.35, 70.22, ['Kerguelen Islands', '凱爾蓋朗島', '凯尔盖朗', 'ケルゲレン諸島', '케르켈렌']],
  'Indian/Mahe': [-4.67, 55.47, ['Mahé', '馬埃島', '马埃岛', 'マヘ', '마헤']],
  'Indian/Maldives': [4.17, 73.5, ['Maldives', '馬爾地夫', '马尔代夫', 'モルディブ', '몰디브']],
  'Indian/Mauritius': [-20.17, 57.5, ['Mauritius', '模里西斯', '毛里求斯', 'モーリシャス', '모리셔스']],
  'Indian/Mayotte': [-12.78, 45.23, ['Mayotte', '馬約特島', '马约特', 'マヨット', '메요트']],
  'Indian/Reunion': [-20.87, 55.47, ['Réunion', '留尼旺島', '留尼汪', 'レユニオン', '레위니옹']],
  'Pacific/Apia': [-13.83, -171.73, ['Apia', '阿皮亞', '阿皮亚', 'アピア', '아피아']],
  'Pacific/Auckland': [-36.87, 174.77, ['Auckland', '奧克蘭', '奥克兰', 'オークランド', '오클랜드']],
  'Pacific/Bougainville': [-6.22, 155.57, ['Bougainville', '布干維爾', '布干维尔', 'ブーゲンビル', '부갱빌']],
  'Pacific/Chatham': [-43.95, -176.55, ['Chatham Islands', '查坦', '查塔姆', 'チャタム', '채텀']],
  'Pacific/Chuuk': [7.42, 151.78, ['Chuuk', '楚克', '特鲁克群岛', 'チューク', '트루크']],
  'Pacific/Easter': [-27.15, -109.43, ['Easter Island', '復活島', '复活节岛', 'イースター島', '이스터 섬']],
  'Pacific/Efate': [-17.67, 168.42, ['Efate', '埃法特', '埃法特', 'エフェテ島', '에파테']],
  'Pacific/Fakaofo': [-9.37, -171.23, ['Fakaofo', '法考福', '法考福', 'ファカオフォ', '파카오푸']],
  'Pacific/Fiji': [-18.13, 178.42, ['Fiji', '斐濟', '斐济', 'フィジー', '피지']],
  'Pacific/Funafuti': [-8.52, 179.22, ['Funafuti', '富那富提', '富纳富提', 'フナフティ', '푸나푸티']],
  'Pacific/Galapagos': [-0.9, -89.6, ['Galápagos Islands', '加拉巴哥群島', '科隆群岛', 'ガラパゴス', '갈라파고스']],
  'Pacific/Gambier': [-23.13, -134.95, ['Gambier', '甘比爾群島', '甘比尔', 'ガンビエ諸島', '감비어']],
  'Pacific/Guadalcanal': [-9.53, 160.2, ['Guadalcanal', '瓜達康納爾島', '瓜达尔卡纳尔', 'ガダルカナル', '과달카날']],
  'Pacific/Guam': [13.47, 144.75, ['Guam', '關島', '关岛', 'グアム', '괌']],
  'Pacific/Honolulu': [21.31, -157.86, ['Honolulu', '檀香山', '檀香山', 'ホノルル', '호놀룰루']],
  'Pacific/Kanton': [-2.78, -171.72, ['Canton Island', '坎頓島', '坎顿岛', 'カントン島', '칸톤']],
  'Pacific/Kiritimati': [1.87, -157.33, ['Kiritimati', '基里地馬地島', '基里地马地岛', 'キリスィマスィ島', '키리티마티']],
  'Pacific/Kosrae': [5.32, 162.98, ['Kosrae', '科斯瑞', '库赛埃', 'コスラエ', '코스레']],
  'Pacific/Kwajalein': [9.08, 167.33, ['Kwajalein Atoll', '瓜加林島', '夸贾林', 'クェゼリン', '콰잘렌']],
  'Pacific/Majuro': [7.15, 171.2, ['Majuro', '馬朱諾', '马朱罗', 'マジュロ', '마주로']],
  'Pacific/Marquesas': [-9.0, -139.5, ['Marquesas Islands', '馬可薩斯島', '马克萨斯', 'マルキーズ', '마퀘사스']],
  'Pacific/Midway': [28.22, -177.37, ['Midway Atoll', '中途島', '中途岛', 'ミッドウェー島', '미드웨이']],
  'Pacific/Nauru': [-0.52, 166.92, ['Nauru', '諾魯', '瑙鲁', 'ナウル', '나우루']],
  'Pacific/Niue': [-19.02, -169.92, ['Niue', '紐埃島', '纽埃', 'ニウエ', '니우에']],
  'Pacific/Norfolk': [-29.05, 167.97, ['Norfolk Island', '諾福克', '诺福克', 'ノーフォーク島', '노퍽']],
  'Pacific/Noumea': [-22.27, 166.45, ['Nouméa', '諾美亞', '努美阿', 'ヌメア', '누메아']],
  'Pacific/Pago_Pago': [-14.27, -170.7, ['Pago Pago', '巴哥巴哥', '帕果帕果', 'パゴパゴ', '파고파고']],
  'Pacific/Palau': [7.33, 134.48, ['Palau', '帛琉', '帕劳', 'パラオ', '팔라우']],
  'Pacific/Pitcairn': [-25.07, -130.08, ['Pitcairn Islands', '皮特肯群島', '皮特凯恩', 'ピトケアン諸島', '핏케언']],
  'Pacific/Pohnpei': [6.97, 158.22, ['Pohnpei', '波納佩', '波纳佩岛', 'ポンペイ島', '포나페']],
  'Pacific/Port_Moresby': [-9.5, 147.17, ['Port Moresby', '莫士比港', '莫尔兹比港', 'ポートモレスビー', '포트모르즈비']],
  'Pacific/Rarotonga': [-21.23, -159.77, ['Rarotonga', '拉羅湯加', '拉罗汤加', 'ラロトンガ', '라로통가']],
  'Pacific/Saipan': [15.2, 145.75, ['Saipan', '塞班', '塞班', 'サイパン', '사이판']],
  'Pacific/Tahiti': [-17.53, -149.57, ['Tahiti', '大溪地', '塔希提', 'タヒチ', '타히티']],
  'Pacific/Tarawa': [1.42, 173.0, ['Tarawa', '塔拉瓦', '塔拉瓦', 'タラワ', '타라와']],
  'Pacific/Tongatapu': [-21.13, -175.2, ['Tongatapu', '東加塔布島', '东加塔布', 'トンガタプ', '통가타푸']],
  'Pacific/Wake': [19.28, 166.62, ['Wake Island', '威克', '威克', 'ウェーク島', '웨이크']],
  'Pacific/Wallis': [-13.3, -176.17, ['Wallis & Futuna', '瓦利斯', '瓦利斯', 'ウォリス諸島', '월리스']],
}

export const ZONE_ALIASES: Readonly<Record<string, string>> = {
  'Africa/Asmera': 'Africa/Asmara',
  'Africa/Timbuktu': 'Africa/Bamako',
  'America/Argentina/ComodRivadavia': 'America/Argentina/Catamarca',
  'America/Atka': 'America/Adak',
  'America/Buenos_Aires': 'America/Argentina/Buenos_Aires',
  'America/Catamarca': 'America/Argentina/Catamarca',
  'America/Coral_Harbour': 'America/Atikokan',
  'America/Cordoba': 'America/Argentina/Cordoba',
  'America/Ensenada': 'America/Tijuana',
  'America/Fort_Wayne': 'America/Indiana/Indianapolis',
  'America/Godthab': 'America/Nuuk',
  'America/Indianapolis': 'America/Indiana/Indianapolis',
  'America/Jujuy': 'America/Argentina/Jujuy',
  'America/Knox_IN': 'America/Indiana/Knox',
  'America/Louisville': 'America/Kentucky/Louisville',
  'America/Mendoza': 'America/Argentina/Mendoza',
  'America/Montreal': 'America/Toronto',
  'America/Nipigon': 'America/Toronto',
  'America/Pangnirtung': 'America/Iqaluit',
  'America/Porto_Acre': 'America/Rio_Branco',
  'America/Rainy_River': 'America/Winnipeg',
  'America/Rosario': 'America/Argentina/Cordoba',
  'America/Santa_Isabel': 'America/Tijuana',
  'America/Shiprock': 'America/Denver',
  'America/Thunder_Bay': 'America/Toronto',
  'America/Virgin': 'America/St_Thomas',
  'America/Yellowknife': 'America/Edmonton',
  'Antarctica/South_Pole': 'Antarctica/McMurdo',
  'Asia/Ashkhabad': 'Asia/Ashgabat',
  'Asia/Calcutta': 'Asia/Kolkata',
  'Asia/Choibalsan': 'Asia/Ulaanbaatar',
  'Asia/Chongqing': 'Asia/Shanghai',
  'Asia/Chungking': 'Asia/Shanghai',
  'Asia/Dacca': 'Asia/Dhaka',
  'Asia/Harbin': 'Asia/Shanghai',
  'Asia/Istanbul': 'Europe/Istanbul',
  'Asia/Kashgar': 'Asia/Urumqi',
  'Asia/Katmandu': 'Asia/Kathmandu',
  'Asia/Macao': 'Asia/Macau',
  'Asia/Rangoon': 'Asia/Yangon',
  'Asia/Saigon': 'Asia/Ho_Chi_Minh',
  'Asia/Tel_Aviv': 'Asia/Jerusalem',
  'Asia/Thimbu': 'Asia/Thimphu',
  'Asia/Ujung_Pandang': 'Asia/Makassar',
  'Asia/Ulan_Bator': 'Asia/Ulaanbaatar',
  'Atlantic/Faeroe': 'Atlantic/Faroe',
  'Atlantic/Jan_Mayen': 'Arctic/Longyearbyen',
  'Australia/ACT': 'Australia/Sydney',
  'Australia/Canberra': 'Australia/Sydney',
  'Australia/Currie': 'Australia/Hobart',
  'Australia/LHI': 'Australia/Lord_Howe',
  'Australia/NSW': 'Australia/Sydney',
  'Australia/North': 'Australia/Darwin',
  'Australia/Queensland': 'Australia/Brisbane',
  'Australia/South': 'Australia/Adelaide',
  'Australia/Tasmania': 'Australia/Hobart',
  'Australia/Victoria': 'Australia/Melbourne',
  'Australia/West': 'Australia/Perth',
  'Australia/Yancowinna': 'Australia/Broken_Hill',
  'Brazil/Acre': 'America/Rio_Branco',
  'Brazil/DeNoronha': 'America/Noronha',
  'Brazil/East': 'America/Sao_Paulo',
  'Brazil/West': 'America/Manaus',
  'CET': 'Europe/Brussels',
  'CST6CDT': 'America/Chicago',
  'Canada/Atlantic': 'America/Halifax',
  'Canada/Central': 'America/Winnipeg',
  'Canada/East-Saskatchewan': 'America/Regina',
  'Canada/Eastern': 'America/Toronto',
  'Canada/Mountain': 'America/Edmonton',
  'Canada/Newfoundland': 'America/St_Johns',
  'Canada/Pacific': 'America/Vancouver',
  'Canada/Saskatchewan': 'America/Regina',
  'Canada/Yukon': 'America/Whitehorse',
  'Chile/Continental': 'America/Santiago',
  'Chile/EasterIsland': 'Pacific/Easter',
  'Cuba': 'America/Havana',
  'EET': 'Europe/Athens',
  'EST': 'America/Panama',
  'EST5EDT': 'America/New_York',
  'Egypt': 'Africa/Cairo',
  'Eire': 'Europe/Dublin',
  'Europe/Belfast': 'Europe/London',
  'Europe/Kiev': 'Europe/Kyiv',
  'Europe/Nicosia': 'Asia/Nicosia',
  'Europe/Tiraspol': 'Europe/Chisinau',
  'Europe/Uzhgorod': 'Europe/Kyiv',
  'Europe/Zaporozhye': 'Europe/Kyiv',
  'GB': 'Europe/London',
  'GB-Eire': 'Europe/London',
  'HST': 'Pacific/Honolulu',
  'Hongkong': 'Asia/Hong_Kong',
  'Iceland': 'Atlantic/Reykjavik',
  'Iran': 'Asia/Tehran',
  'Israel': 'Asia/Jerusalem',
  'Jamaica': 'America/Jamaica',
  'Japan': 'Asia/Tokyo',
  'Kwajalein': 'Pacific/Kwajalein',
  'Libya': 'Africa/Tripoli',
  'MET': 'Europe/Brussels',
  'MST': 'America/Phoenix',
  'MST7MDT': 'America/Denver',
  'Mexico/BajaNorte': 'America/Tijuana',
  'Mexico/BajaSur': 'America/Mazatlan',
  'Mexico/General': 'America/Mexico_City',
  'NZ': 'Pacific/Auckland',
  'NZ-CHAT': 'Pacific/Chatham',
  'Navajo': 'America/Denver',
  'PRC': 'Asia/Shanghai',
  'PST8PDT': 'America/Los_Angeles',
  'Pacific/Enderbury': 'Pacific/Kanton',
  'Pacific/Johnston': 'Pacific/Honolulu',
  'Pacific/Ponape': 'Pacific/Pohnpei',
  'Pacific/Samoa': 'Pacific/Pago_Pago',
  'Pacific/Truk': 'Pacific/Chuuk',
  'Pacific/Yap': 'Pacific/Chuuk',
  'Poland': 'Europe/Warsaw',
  'Portugal': 'Europe/Lisbon',
  'ROC': 'Asia/Taipei',
  'ROK': 'Asia/Seoul',
  'Singapore': 'Asia/Singapore',
  'Turkey': 'Europe/Istanbul',
  'US/Alaska': 'America/Anchorage',
  'US/Aleutian': 'America/Adak',
  'US/Arizona': 'America/Phoenix',
  'US/Central': 'America/Chicago',
  'US/East-Indiana': 'America/Indiana/Indianapolis',
  'US/Eastern': 'America/New_York',
  'US/Hawaii': 'Pacific/Honolulu',
  'US/Indiana-Starke': 'America/Indiana/Knox',
  'US/Michigan': 'America/Detroit',
  'US/Mountain': 'America/Denver',
  'US/Pacific': 'America/Los_Angeles',
  'US/Pacific-New': 'America/Los_Angeles',
  'US/Samoa': 'Pacific/Pago_Pago',
  'W-SU': 'Europe/Moscow',
  'WET': 'Europe/Lisbon',
}
